apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "roundhouse.api.fullname" . }}-server-data
  labels:
    {{- include "roundhouse.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.api.storage.serverData.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.api.storage.serverData.size }}
  {{- with .Values.api.storage.serverData.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
