{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "roundhouse.postgres.fullname" . }}
  labels:
    {{- include "roundhouse.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    {{- include "roundhouse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "roundhouse.postgres.fullname" . }}
  labels:
    {{- include "roundhouse.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  serviceName: {{ include "roundhouse.postgres.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "roundhouse.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "roundhouse.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.auth.user | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.auth.database | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "roundhouse.fullname" . }}-db
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.postgres.auth.user }}"]
            initialDelaySeconds: 5
            periodSeconds: 5
          {{- with .Values.postgres.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - {{ .Values.postgres.storage.accessMode | default "ReadWriteOnce" }}
        resources:
          requests:
            storage: {{ .Values.postgres.storage.size }}
        {{- with .Values.postgres.storage.storageClass }}
        storageClassName: {{ . | quote }}
        {{- end }}
{{- end }}
