{{- if .Values.workloadsNamespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.workloadsNamespace.name }}
  labels:
    {{- include "roundhouse.labels" . | nindent 4 }}
{{- end }}
